spring:
  profiles:
    active: local
  config:
    import: optional:file:.env[.properties]
  application:
    name: springbatch-dashboard
  docker:
    compose:
      lifecycle-management: start_only
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

app:
  datasources:
    - name: Localhost Test
      url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB}?readOnly=true
      username: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
    - name: Localhost User ETL
      url: jdbc:postgresql://localhost:54320/mydatabase?readOnly=true
      username: myuser
      password: secret