spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}

app:
  cors:
    allowed-origins: http://localhost:5173
  oauth2:
    success-url: http://localhost:5173/overview
