spring:
  config:
    import: optional:file:.env[.properties]
  docker:
    compose:
      lifecycle-management: start_only
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}

app:
  cors:
    allowed-origins: http://localhost:5173
  oauth2:
    success-url: http://localhost:5173/overview
  datasources:
    - name: Localhost Postgres
      type: POSTGRESQL
      url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB}?readOnly=true
      username: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
    - name: Localhost MySQL
      type: MYSQL
      url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB}
      username: ${MYSQL_USER}
      password: ${MYSQL_PASSWORD}
    - name: Localhost Oracle
      type: ORACLE
      url: jdbc:oracle:thin:@//${ORACLE_HOST:localhost}:${ORACLE_PORT:1521}/${ORACLE_DB:FREEPDB1}
      username: ${ORACLE_USER}
      password: ${ORACLE_PASSWORD}
